name: snatch

on:
  push:
    branches:
      - main
#   schedule:
#     - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - run: npm install
<<<<<<< HEAD
<<<<<<< HEAD
      - run: npm run snatch-plugins
#       - run: npm run snatch-files
=======
=======
>>>>>>> parent of 026a163a97 (Update snatch.yml)
      - run: npm run snatch-files
>>>>>>> parent of 026a163a97 (Update snatch.yml)

      - run: |
          git add .
          git commit -m 'snatched'
          git push origin main
