name: snatch

on:
  push:
    branches:
      - one-json-test
# schedule:
#   - cron: '0 6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm run snatch-plugins
      # - run: npm run snatch-files

      - run: |
          rm -rf .git
          git clone --single-branch --branch empty-branch --depth 1 https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git empty-branch
          cd empty-branch
          git config user.email actions@github.com
          git config user.name 'GitHub Actions'
          cp -r ../data/. .
          git add .
          git commit -m 'snatched'
          git push origin empty-branch
