name: snatch

on:
 push:
  branches:
   - main
 schedule:
   - cron: "0 16,18,19 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: INSTALL AND BUILD
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - run: npm install
      - run: npm start

      - run: git checkout --orphan gh-pages
      - run: git rm -r --cached .
      - run: git commit --allow-empty -m 'Create gh-pages'
      - run: git checkout master --force

